services:
  expo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: farmer-helper
    ports:
      - "19000:19000" 
      - "19001:19001" 
      - "19002:19002"  
      - "8081:8081"
    volumes:
      - .:/app      
      - /app/node_modules 
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - REACT_NATIVE_PACKAGER_HOSTNAME=${HOST_IP}
    stdin_open: true
    tty: true
